services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiSearch\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Dto/*'

  Maispace\MaiSearch\Service\IndexerRegistry:
    public: true
    tags:
      - name: 'maispace.search.indexer_registry'

  Maispace\MaiSearch\Service\ResultFormatterRegistry:
    public: true
    tags:
      - name: 'maispace.search.formatter_registry'

  Maispace\MaiSearch\Indexer\PageIndexer:
    tags:
      - name: 'maispace.search.indexer'
      - name: 'maispace.search.result_formatter'

  Maispace\MaiSearch\Controller\SearchController:
    public: true

  Maispace\MaiSearch\Scheduler\FullReindexTask:
    public: true

  dashboard.widget.solr_health:
    class: 'Maispace\MaiSearch\Widget\SolrHealthWidget'
    tags:
      - name: dashboard.widget
        identifier: 'solrHealth'
        groupNames: 'systemInfo'
        title: 'LLL:EXT:mai_search/Resources/Private/Language/locallang_dashboard.xlf:widgets.solrHealth.title'
        description: 'LLL:EXT:mai_search/Resources/Private/Language/locallang_dashboard.xlf:widgets.solrHealth.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'medium'
