services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiSearch\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Dto/*'

  Maispace\MaiSearch\Service\IndexerRegistry:
    public: true
    tags:
      - name: 'maispace.search.indexer_registry'

  Maispace\MaiSearch\Service\ResultFormatterRegistry:
    public: true
    tags:
      - name: 'maispace.search.formatter_registry'

  Maispace\MaiSearch\Controller\SearchController:
    public: true

  Maispace\MaiSearch\Scheduler\FullReindexTask:
    public: true
